name = "autoscript-auth-worker"
main = "src/index.js"
compatibility_date = "2026-04-09"
workers_dev = true

[vars]
BASE_URL = "https://autoscript-auth-worker.bravinlite.workers.dev"
TOKEN_TTL_SECONDS = "300"
PAYLOAD_OBJECT_KEY = "payload.sh"

[[kv_namespaces]]
binding = "LICENSES"
id = "ef7cc518a5f346d2b18d03467185e14d"

[[r2_buckets]]
binding = "PAYLOAD_BUCKET"
bucket_name = "autoscript-payloads"
